-- OSP Language Pack Foundation Seed
-- Purpose:
-- - Seed active language packs.
-- - Seed starter traveler translation keys.
-- - Seed English default published values.
-- - Seed Filipino proof values for dictionary rendering validation.
--
-- Safe to rerun.

insert into "LanguagePack" ("id","languageCode","label","group","isActive","launchPriority","createdAt","updatedAt") values
('lang_en','en','English','International',true,1,now(),now()),
('lang_zh_hant','zh-Hant','Chinese Traditional','International',true,2,now(),now()),
('lang_zh_hans','zh-Hans','Chinese Simplified','International',true,3,now(),now()),
('lang_ko','ko','Korean','International',true,4,now(),now()),
('lang_ja','ja','Japanese','International',true,5,now(),now()),
('lang_es','es','Spanish','European',true,6,now(),now()),
('lang_fr','fr','French','European',true,7,now(),now()),
('lang_de','de','German','European',true,8,now(),now()),
('lang_it','it','Italian','European',true,9,now(),now()),
('lang_pt','pt','Portuguese','European',true,10,now(),now()),
('lang_nl','nl','Dutch','European',true,11,now(),now()),
('lang_sv','sv','Swedish','European',true,12,now(),now()),
('lang_no','no','Norwegian','European',true,13,now(),now()),
('lang_da','da','Danish','European',true,14,now(),now()),
('lang_pl','pl','Polish','European',true,15,now(),now()),
('lang_fil','fil','Filipino','Filipino',true,16,now(),now()),
('lang_ceb','ceb','Bisaya / Cebuano','Filipino',true,17,now(),now()),
('lang_sgd','sgd','Surigaonon','Filipino',true,18,now(),now())
on conflict ("languageCode") do update set
"label"=excluded."label",
"group"=excluded."group",
"isActive"=excluded."isActive",
"launchPriority"=excluded."launchPriority",
"updatedAt"=now();

insert into "LanguageTranslationKey" ("id","key","scope","defaultText","description","isActive","createdAt","updatedAt") values
('ltk_home_title','home.hero.title','traveler','Trips Active. Pass Ready.','OSP home hero title',true,now(),now()),
('ltk_home_show_qr','home.cta.showQr','traveler','Show My QR','OSP home QR CTA',true,now(),now()),
('ltk_home_passport_map','home.cta.passportMap','traveler','Open Passport Map','OSP home passport map CTA',true,now(),now()),
('ltk_home_hero_active_title','home.hero.active.title','traveler','Trip Active.\nPass Ready.','OSP home active hero title',true,now(),now()),
('ltk_home_hero_active_body','home.hero.active.body','traveler','Access your trip status,\npass, clearance, and\npayment in one place.','OSP home active hero body',true,now(),now()),
('ltk_home_hero_active_traveler_label','home.hero.active.travelerLabel','traveler','Verified Traveler','OSP home active traveler label',true,now(),now()),
('ltk_home_hero_registration_required_title','home.hero.registrationRequired.title','traveler','Trip On File.\nRegistration Required.','OSP home registration required hero title',true,now(),now()),
('ltk_home_hero_registration_required_body','home.hero.registrationRequired.body','traveler','Complete your traveler trip registration first so your pass can move forward.','OSP home registration required hero body',true,now(),now()),
('ltk_home_hero_registration_required_traveler_label','home.hero.registrationRequired.travelerLabel','traveler','Traveler On File','OSP home registration required traveler label',true,now(),now()),
('ltk_home_hero_manifest_required_title','home.hero.manifestRequired.title','traveler','Trip On File.\nManifest Listing Required.','OSP home manifest required hero title',true,now(),now()),
('ltk_home_hero_manifest_required_body','home.hero.manifestRequired.body','traveler','Your registration is on file, but you are not yet listed in the manifest for this trip.','OSP home manifest required hero body',true,now(),now()),
('ltk_home_hero_manifest_required_traveler_label','home.hero.manifestRequired.travelerLabel','traveler','Traveler On File','OSP home manifest required traveler label',true,now(),now()),
('ltk_home_hero_pass_pending_title','home.hero.passPending.title','traveler','Trip Found.\nPass Pending.','OSP home pass pending hero title',true,now(),now()),
('ltk_home_hero_pass_pending_body','home.hero.passPending.body','traveler','Your registration is on file. Keep checking your latest trip status as your pass moves forward.','OSP home pass pending hero body',true,now(),now()),
('ltk_home_hero_pass_pending_traveler_label','home.hero.passPending.travelerLabel','traveler','Traveler On File','OSP home pass pending traveler label',true,now(),now()),
('ltk_home_hero_clearance_pending_title','home.hero.clearancePending.title','traveler','Trip On File.\nClearance Pending.','OSP home clearance pending hero title',true,now(),now()),
('ltk_home_hero_clearance_pending_body','home.hero.clearancePending.body','traveler','Your pass may be issued, but clearance is still under review before trip readiness is confirmed.','OSP home clearance pending hero body',true,now(),now()),
('ltk_home_hero_clearance_pending_traveler_label','home.hero.clearancePending.travelerLabel','traveler','Traveler On File','OSP home clearance pending traveler label',true,now(),now()),
('ltk_home_hero_payment_pending_title','home.hero.paymentPending.title','traveler','Trip On File.\nPayment Pending.','OSP home payment pending hero title',true,now(),now()),
('ltk_home_hero_payment_pending_body','home.hero.paymentPending.body','traveler','Access your trip status,\npass, clearance, and\npayment in one place.','OSP home payment pending hero body',true,now(),now()),
('ltk_home_hero_payment_pending_traveler_label','home.hero.paymentPending.travelerLabel','traveler','Payment Pending','OSP home payment pending traveler label',true,now(),now()),
('ltk_home_hero_empty_title','home.hero.empty.title','traveler','Start Your\nOne Siargao Pass.','OSP home empty hero title',true,now(),now()),
('ltk_home_hero_empty_body','home.hero.empty.body','traveler','Access your trip status,\npass, clearance, and\npayment in one place.','OSP home empty hero body',true,now(),now()),
('ltk_home_hero_empty_traveler_label','home.hero.empty.travelerLabel','traveler','Traveler Access','OSP home empty traveler label',true,now(),now()),
('ltk_home_header_official_traveler_pass','home.header.officialTravelerPass','traveler','Official Traveler Pass','OSP home header pass label',true,now(),now()),
('ltk_home_header_language_aria','home.header.language.ariaLabel','traveler','Open language selector','OSP home language aria label',true,now(),now()),
('ltk_home_header_currency_aria','home.header.currency.ariaLabel','traveler','Open currency selector','OSP home currency aria label',true,now(),now()),
('ltk_home_header_assistant_aria','home.header.assistant.ariaLabel','traveler','Open OSP Travel Assistant','OSP home assistant aria label',true,now(),now()),
('ltk_home_header_notifications_aria','home.header.notifications.ariaLabel','traveler','Notifications','OSP home notifications aria label',true,now(),now()),
('ltk_home_pass_card_pass_code','home.passCard.passCode','traveler','Pass Code','OSP home pass card pass code label',true,now(),now()),
('ltk_home_pass_card_valid_dates','home.passCard.validDates','traveler','Valid Dates','OSP home pass card valid dates label',true,now(),now()),
('ltk_home_pass_card_badge_prefix','home.passCard.badgePrefix','traveler','PASS','OSP home pass card badge prefix',true,now(),now()),
('ltk_home_status_clearance','home.status.clearance','traveler','Clearance Status','OSP home clearance status label',true,now(),now()),
('ltk_home_status_payment','home.status.payment','traveler','Payment Status','OSP home payment status label',true,now(),now()),
('ltk_home_status_pass','home.status.pass','traveler','Pass Status','OSP home pass status label',true,now(),now()),
('ltk_home_status_trip_dates','home.status.tripDates','traveler','Trip Dates','OSP home trip dates label',true,now(),now()),
('ltk_home_reassurance_message','home.reassurance.message','traveler','Your pass, clearance, payment, and trip records stay connected to your One Siargao Pass profile.','OSP home reassurance message',true,now(),now()),
('ltk_home_journey_title','home.journey.title','traveler','Continue Your Journey','OSP home journey section title',true,now(),now()),
('ltk_home_journey_trips_title','home.journey.trips.title','traveler','Trips','OSP home trips journey title',true,now(),now()),
('ltk_home_journey_trips_subtitle','home.journey.trips.subtitle','traveler','Plans & records','OSP home trips journey subtitle',true,now(),now()),
('ltk_home_journey_payments_title','home.journey.payments.title','traveler','Payments','OSP home payments journey title',true,now(),now()),
('ltk_home_journey_payments_subtitle','home.journey.payments.subtitle','traveler','Status & receipts','OSP home payments journey subtitle',true,now(),now()),
('ltk_home_journey_passport_map_title','home.journey.passportMap.title','traveler','Passport Map','OSP home passport map journey title',true,now(),now()),
('ltk_home_journey_passport_map_subtitle','home.journey.passportMap.subtitle','traveler','Trails & stamps','OSP home passport map journey subtitle',true,now(),now()),
('ltk_home_journey_checkpoints_title','home.journey.checkpoints.title','traveler','Checkpoints','OSP home checkpoints journey title',true,now(),now()),
('ltk_home_journey_checkpoints_subtitle','home.journey.checkpoints.subtitle','traveler','QR & access state','OSP home checkpoints journey subtitle',true,now(),now()),
('ltk_home_bottom_nav_home','home.bottomNav.home','traveler','Home','OSP home bottom nav home label',true,now(),now()),
('ltk_home_bottom_nav_trips','home.bottomNav.trips','traveler','Trips','OSP home bottom nav trips label',true,now(),now()),
('ltk_home_bottom_nav_payments','home.bottomNav.payments','traveler','Payments','OSP home bottom nav payments label',true,now(),now()),
('ltk_home_bottom_nav_profile','home.bottomNav.profile','traveler','Profile','OSP home bottom nav profile label',true,now(),now()),
('ltk_home_pass_open_qr_aria','home.pass.openQr.ariaLabel','traveler','Open active pass QR','OSP home active pass QR aria label',true,now(),now()),
('ltk_settings_title','settings.title','traveler','Traveler Controls','Traveler settings screen title',true,now(),now()),
('ltk_settings_language_title','settings.language.title','traveler','Choose your travel language','Language settings title',true,now(),now()),
('ltk_trips_title','trips.title','traveler','My Trips','Traveler trips title',true,now(),now()),
('ltk_trip_detail_title','tripDetail.title','traveler','View Trip','Trip detail screen title',true,now(),now()),
('ltk_payment_detail_title','paymentDetail.title','traveler','Payment Detail','Payment detail screen title',true,now(),now()),
('ltk_spm_title','spm.title','traveler','Your Siargao Journey, Mapped','SPM hero title',true,now(),now()),
('ltk_pass_header_eyebrow','pass.header.eyebrow','traveler','Official Traveler Pass','Traveler pass header eyebrow',true,now(),now()),
('ltk_pass_header_title','pass.header.title','traveler','OSP Pass','Traveler pass header title',true,now(),now()),
('ltk_pass_header_body','pass.header.body','traveler','View your issued pass, QR credential, trip status, and Passport Map bridge.','Traveler pass header body',true,now(),now()),
('ltk_pass_nav_home','pass.nav.home','traveler','Home','Traveler pass nav home label',true,now(),now()),
('ltk_pass_nav_my_trips','pass.nav.myTrips','traveler','My Trips','Traveler pass nav trips label',true,now(),now()),
('ltk_pass_nav_passport_map','pass.nav.passportMap','traveler','Passport Map','Traveler pass nav passport map label',true,now(),now()),
('ltk_pass_nav_logout','pass.nav.logout','traveler','Logout','Traveler pass nav logout label',true,now(),now()),
('ltk_pass_access_note_title','pass.accessNote.title','traveler','Pass Access Note','Traveler pass access note title',true,now(),now()),
('ltk_pass_access_note_body1','pass.accessNote.body1','traveler','This page uses the authenticated session to load the traveler pass view.','Traveler pass access note body 1',true,now(),now()),
('ltk_pass_access_note_body2','pass.accessNote.body2','traveler','If an issued pass already exists, it is prioritized. Otherwise the latest traveler trip is checked for pass eligibility.','Traveler pass access note body 2',true,now(),now()),
('ltk_pass_load_error_title','pass.loadError.title','traveler','Load Error','Traveler pass load error title',true,now(),now()),
('ltk_pass_empty_title','pass.empty.title','traveler','No Trips Available','Traveler pass empty title',true,now(),now()),
('ltk_pass_empty_body','pass.empty.body','traveler','No traveler trip is available yet for pass viewing.','Traveler pass empty body',true,now(),now()),
('ltk_pass_readiness_section_title','pass.readiness.sectionTitle','traveler','Pass Readiness','Traveler pass readiness section title',true,now(),now()),
('ltk_pass_readiness_no_trip_title','pass.readiness.noTrip.title','traveler','No Trip Available','Traveler pass no trip title',true,now(),now()),
('ltk_pass_readiness_no_trip_body','pass.readiness.noTrip.body','traveler','No traveler trip is available yet for pass viewing.','Traveler pass no trip body',true,now(),now()),
('ltk_pass_readiness_ready_title','pass.readiness.ready.title','traveler','Pass Ready','Traveler pass ready title',true,now(),now()),
('ltk_pass_readiness_ready_body','pass.readiness.ready.body','traveler','Your pass is on file and ready for operational use.','Traveler pass ready body',true,now(),now()),
('ltk_pass_readiness_on_record_title','pass.readiness.onRecord.title','traveler','Pass On Record','Traveler pass on record title',true,now(),now()),
('ltk_pass_readiness_pending_title','pass.readiness.pending.title','traveler','Pass Pending','Traveler pass pending title',true,now(),now()),
('ltk_pass_readiness_pending_body','pass.readiness.pending.body','traveler','Your traveler pass is not yet available. Check the status summary below for the next requirement.','Traveler pass pending body',true,now(),now()),
('ltk_pass_qr_section_title','pass.qr.sectionTitle','traveler','QR Credential','Traveler pass QR section title',true,now(),now()),
('ltk_pass_qr_active_label','pass.qr.activeLabel','traveler','Active Pass QR Credential','Traveler pass QR active label',true,now(),now()),
('ltk_pass_qr_not_ready','pass.qr.notReady','traveler','QR is on record but not ready for operational use yet.','Traveler pass QR not ready message',true,now(),now()),
('ltk_pass_qr_unavailable','pass.qr.unavailable','traveler','QR token is not available for this pass yet.','Traveler pass QR unavailable message',true,now(),now()),
('ltk_pass_action_required_title','pass.actionRequired.title','traveler','Action Required','Traveler pass action required title',true,now(),now()),
('ltk_pass_blocked_title','pass.blocked.title','traveler','Pass Blocked','Traveler pass blocked title',true,now(),now()),
('ltk_pass_spm_section_title','pass.spm.sectionTitle','traveler','Siargao Passport Map','Traveler pass SPM section title',true,now(),now()),
('ltk_pass_spm_eyebrow','pass.spm.eyebrow','traveler','Second Screen','Traveler pass SPM eyebrow',true,now(),now()),
('ltk_pass_spm_title','pass.spm.title','traveler','Continue to your Passport Map','Traveler pass SPM title',true,now(),now()),
('ltk_pass_spm_body','pass.spm.body','traveler','Your SPM trail progress uses governed OSP QR, stamp, pass, and trip records when available. Preview layout cards may appear only to preserve the approved map geometry.','Traveler pass SPM body',true,now(),now()),
('ltk_pass_spm_cta','pass.spm.cta','traveler','Open Siargao Passport Map','Traveler pass SPM CTA',true,now(),now()),
('ltk_pass_status_section_title','pass.status.sectionTitle','traveler','Key Status Summary','Traveler pass status section title',true,now(),now())
on conflict ("key") do update set
"scope"=excluded."scope",
"defaultText"=excluded."defaultText",
"description"=excluded."description",
"isActive"=excluded."isActive",
"updatedAt"=now();

insert into "LanguageTranslationValue" ("id","languagePackId","translationKeyId","value","status","createdAt","updatedAt")
select replace('ltv_' || lp."languageCode" || '_' || tk."id", '-', '_'), lp."id", tk."id", tk."defaultText", 'PUBLISHED', now(), now()
from "LanguagePack" lp
cross join "LanguageTranslationKey" tk
where lp."languageCode" = 'en'
on conflict ("languagePackId","translationKeyId") do update set
"value"=excluded."value",
"status"='PUBLISHED',
"updatedAt"=now();

insert into "LanguageTranslationValue" ("id","languagePackId","translationKeyId","value","status","createdAt","updatedAt") values
('ltv_fil_ltk_settings_title','lang_fil','ltk_settings_title','Mga Kontrol ng Traveler','PUBLISHED',now(),now()),
('ltv_fil_ltk_settings_language_title','lang_fil','ltk_settings_language_title','Piliin ang travel language mo','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_title','lang_fil','ltk_home_title','Trip Aktibo. Pass Handa.','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_show_qr','lang_fil','ltk_home_show_qr','Ipakita ang QR','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_passport_map','lang_fil','ltk_home_passport_map','Buksan ang Passport Map','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_hero_active_title','lang_fil','ltk_home_hero_active_title','Trip Aktibo.\nPass Handa.','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_hero_active_body','lang_fil','ltk_home_hero_active_body','Tingnan ang trip status,\npass, clearance, at\npayment mo sa isang lugar.','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_hero_active_traveler_label','lang_fil','ltk_home_hero_active_traveler_label','Verified Traveler','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_header_official_traveler_pass','lang_fil','ltk_home_header_official_traveler_pass','Official Traveler Pass','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_header_language_aria','lang_fil','ltk_home_header_language_aria','Buksan ang language selector','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_header_currency_aria','lang_fil','ltk_home_header_currency_aria','Buksan ang currency selector','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_header_assistant_aria','lang_fil','ltk_home_header_assistant_aria','Buksan ang OSP Travel Assistant','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_header_notifications_aria','lang_fil','ltk_home_header_notifications_aria','Mga notification','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_pass_card_pass_code','lang_fil','ltk_home_pass_card_pass_code','Pass Code','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_pass_card_valid_dates','lang_fil','ltk_home_pass_card_valid_dates','Valid Dates','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_pass_card_badge_prefix','lang_fil','ltk_home_pass_card_badge_prefix','PASS','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_status_clearance','lang_fil','ltk_home_status_clearance','Clearance Status','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_status_payment','lang_fil','ltk_home_status_payment','Payment Status','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_status_pass','lang_fil','ltk_home_status_pass','Pass Status','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_status_trip_dates','lang_fil','ltk_home_status_trip_dates','Trip Dates','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_reassurance_message','lang_fil','ltk_home_reassurance_message','Nakakonekta ang pass, clearance, payment, at trip records mo sa One Siargao Pass profile mo.','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_title','lang_fil','ltk_home_journey_title','Ipagpatuloy ang Journey Mo','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_trips_title','lang_fil','ltk_home_journey_trips_title','Trips','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_trips_subtitle','lang_fil','ltk_home_journey_trips_subtitle','Plans & records','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_payments_title','lang_fil','ltk_home_journey_payments_title','Payments','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_payments_subtitle','lang_fil','ltk_home_journey_payments_subtitle','Status & receipts','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_passport_map_title','lang_fil','ltk_home_journey_passport_map_title','Passport Map','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_passport_map_subtitle','lang_fil','ltk_home_journey_passport_map_subtitle','Trails & stamps','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_checkpoints_title','lang_fil','ltk_home_journey_checkpoints_title','Checkpoints','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_checkpoints_subtitle','lang_fil','ltk_home_journey_checkpoints_subtitle','QR & access state','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_bottom_nav_home','lang_fil','ltk_home_bottom_nav_home','Home','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_bottom_nav_trips','lang_fil','ltk_home_bottom_nav_trips','Trips','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_bottom_nav_payments','lang_fil','ltk_home_bottom_nav_payments','Payments','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_bottom_nav_profile','lang_fil','ltk_home_bottom_nav_profile','Profile','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_pass_open_qr_aria','lang_fil','ltk_home_pass_open_qr_aria','Buksan ang active pass QR','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_header_eyebrow','lang_fil','ltk_pass_header_eyebrow','Official Traveler Pass','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_header_title','lang_fil','ltk_pass_header_title','OSP Pass','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_header_body','lang_fil','ltk_pass_header_body','Tingnan ang issued pass, QR credential, trip status, at Passport Map bridge mo.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_nav_home','lang_fil','ltk_pass_nav_home','Home','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_nav_my_trips','lang_fil','ltk_pass_nav_my_trips','My Trips','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_nav_passport_map','lang_fil','ltk_pass_nav_passport_map','Passport Map','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_nav_logout','lang_fil','ltk_pass_nav_logout','Logout','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_access_note_title','lang_fil','ltk_pass_access_note_title','Pass Access Note','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_access_note_body1','lang_fil','ltk_pass_access_note_body1','Ginagamit ng page na ito ang authenticated session para i-load ang traveler pass view.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_access_note_body2','lang_fil','ltk_pass_access_note_body2','Kung may issued pass na, iyon ang uunahin. Kung wala pa, iche-check ang latest traveler trip para sa pass eligibility.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_empty_title','lang_fil','ltk_pass_empty_title','Walang Trips Available','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_empty_body','lang_fil','ltk_pass_empty_body','Wala pang traveler trip na available para sa pass viewing.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_readiness_section_title','lang_fil','ltk_pass_readiness_section_title','Pass Readiness','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_readiness_ready_title','lang_fil','ltk_pass_readiness_ready_title','Pass Ready','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_readiness_ready_body','lang_fil','ltk_pass_readiness_ready_body','Naka-record na ang pass mo at ready na para sa operational use.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_readiness_pending_title','lang_fil','ltk_pass_readiness_pending_title','Pass Pending','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_readiness_pending_body','lang_fil','ltk_pass_readiness_pending_body','Hindi pa available ang traveler pass mo. Tingnan ang status summary para sa susunod na requirement.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_qr_section_title','lang_fil','ltk_pass_qr_section_title','QR Credential','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_qr_active_label','lang_fil','ltk_pass_qr_active_label','Active Pass QR Credential','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_qr_not_ready','lang_fil','ltk_pass_qr_not_ready','Naka-record ang QR pero hindi pa ready para sa operational use.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_qr_unavailable','lang_fil','ltk_pass_qr_unavailable','Wala pang QR token para sa pass na ito.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_action_required_title','lang_fil','ltk_pass_action_required_title','Action Required','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_blocked_title','lang_fil','ltk_pass_blocked_title','Pass Blocked','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_spm_section_title','lang_fil','ltk_pass_spm_section_title','Siargao Passport Map','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_spm_eyebrow','lang_fil','ltk_pass_spm_eyebrow','Second Screen','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_spm_title','lang_fil','ltk_pass_spm_title','Magpatuloy sa Passport Map mo','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_spm_body','lang_fil','ltk_pass_spm_body','Ang SPM trail progress mo ay gumagamit ng governed OSP QR, stamp, pass, at trip records kapag available. Preview layout cards ay para mapanatili lang ang approved map geometry.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_spm_cta','lang_fil','ltk_pass_spm_cta','Buksan ang Siargao Passport Map','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_status_section_title','lang_fil','ltk_pass_status_section_title','Key Status Summary','PUBLISHED',now(),now())
on conflict ("languagePackId","translationKeyId") do update set
"value"=excluded."value",
"status"='PUBLISHED',
"updatedAt"=now();
