-- OSP Language Pack Foundation Seed
-- Purpose:
-- - Seed active language packs.
-- - Seed starter traveler translation keys.
-- - Seed English default published values.
-- - Seed Filipino proof values for dictionary rendering validation.
--
-- Safe to rerun.

insert into "LanguagePack" ("id","languageCode","label","group","isActive","launchPriority","createdAt","updatedAt") values
('lang_en','en','English','International',true,1,now(),now()),
('lang_zh_hant','zh-Hant','Chinese Traditional','International',true,2,now(),now()),
('lang_zh_hans','zh-Hans','Chinese Simplified','International',true,3,now(),now()),
('lang_ko','ko','Korean','International',true,4,now(),now()),
('lang_ja','ja','Japanese','International',true,5,now(),now()),
('lang_es','es','Spanish','European',true,6,now(),now()),
('lang_fr','fr','French','European',true,7,now(),now()),
('lang_de','de','German','European',true,8,now(),now()),
('lang_it','it','Italian','European',true,9,now(),now()),
('lang_pt','pt','Portuguese','European',true,10,now(),now()),
('lang_nl','nl','Dutch','European',true,11,now(),now()),
('lang_sv','sv','Swedish','European',true,12,now(),now()),
('lang_no','no','Norwegian','European',true,13,now(),now()),
('lang_da','da','Danish','European',true,14,now(),now()),
('lang_pl','pl','Polish','European',true,15,now(),now()),
('lang_fil','fil','Filipino','Filipino',true,16,now(),now()),
('lang_ceb','ceb','Bisaya / Cebuano','Filipino',true,17,now(),now()),
('lang_sgd','sgd','Surigaonon','Filipino',true,18,now(),now())
on conflict ("languageCode") do update set
"label"=excluded."label",
"group"=excluded."group",
"isActive"=excluded."isActive",
"launchPriority"=excluded."launchPriority",
"updatedAt"=now();

insert into "LanguageTranslationKey" ("id","key","scope","defaultText","description","isActive","createdAt","updatedAt") values
('ltk_home_title','home.hero.title','traveler','Trips Active. Pass Ready.','OSP home hero title',true,now(),now()),
('ltk_home_show_qr','home.cta.showQr','traveler','Show My QR','OSP home QR CTA',true,now(),now()),
('ltk_home_passport_map','home.cta.passportMap','traveler','Open Passport Map','OSP home passport map CTA',true,now(),now()),
('ltk_home_hero_active_title','home.hero.active.title','traveler','Trip Active.\nPass Ready.','OSP home active hero title',true,now(),now()),
('ltk_home_hero_active_body','home.hero.active.body','traveler','Access your trip status,\npass, clearance, and\npayment in one place.','OSP home active hero body',true,now(),now()),
('ltk_home_hero_active_traveler_label','home.hero.active.travelerLabel','traveler','Verified Traveler','OSP home active traveler label',true,now(),now()),
('ltk_home_hero_registration_required_title','home.hero.registrationRequired.title','traveler','Trip On File.\nRegistration Required.','OSP home registration required hero title',true,now(),now()),
('ltk_home_hero_registration_required_body','home.hero.registrationRequired.body','traveler','Complete your traveler trip registration first so your pass can move forward.','OSP home registration required hero body',true,now(),now()),
('ltk_home_hero_registration_required_traveler_label','home.hero.registrationRequired.travelerLabel','traveler','Traveler On File','OSP home registration required traveler label',true,now(),now()),
('ltk_home_hero_manifest_required_title','home.hero.manifestRequired.title','traveler','Trip On File.\nManifest Listing Required.','OSP home manifest required hero title',true,now(),now()),
('ltk_home_hero_manifest_required_body','home.hero.manifestRequired.body','traveler','Your registration is on file, but you are not yet listed in the manifest for this trip.','OSP home manifest required hero body',true,now(),now()),
('ltk_home_hero_manifest_required_traveler_label','home.hero.manifestRequired.travelerLabel','traveler','Traveler On File','OSP home manifest required traveler label',true,now(),now()),
('ltk_home_hero_pass_pending_title','home.hero.passPending.title','traveler','Trip Found.\nPass Pending.','OSP home pass pending hero title',true,now(),now()),
('ltk_home_hero_pass_pending_body','home.hero.passPending.body','traveler','Your registration is on file. Keep checking your latest trip status as your pass moves forward.','OSP home pass pending hero body',true,now(),now()),
('ltk_home_hero_pass_pending_traveler_label','home.hero.passPending.travelerLabel','traveler','Traveler On File','OSP home pass pending traveler label',true,now(),now()),
('ltk_home_hero_clearance_pending_title','home.hero.clearancePending.title','traveler','Trip On File.\nClearance Pending.','OSP home clearance pending hero title',true,now(),now()),
('ltk_home_hero_clearance_pending_body','home.hero.clearancePending.body','traveler','Your pass may be issued, but clearance is still under review before trip readiness is confirmed.','OSP home clearance pending hero body',true,now(),now()),
('ltk_home_hero_clearance_pending_traveler_label','home.hero.clearancePending.travelerLabel','traveler','Traveler On File','OSP home clearance pending traveler label',true,now(),now()),
('ltk_home_hero_payment_pending_title','home.hero.paymentPending.title','traveler','Trip On File.\nPayment Pending.','OSP home payment pending hero title',true,now(),now()),
('ltk_home_hero_payment_pending_body','home.hero.paymentPending.body','traveler','Access your trip status,\npass, clearance, and\npayment in one place.','OSP home payment pending hero body',true,now(),now()),
('ltk_home_hero_payment_pending_traveler_label','home.hero.paymentPending.travelerLabel','traveler','Payment Pending','OSP home payment pending traveler label',true,now(),now()),
('ltk_home_hero_empty_title','home.hero.empty.title','traveler','Start Your\nOne Siargao Pass.','OSP home empty hero title',true,now(),now()),
('ltk_home_hero_empty_body','home.hero.empty.body','traveler','Access your trip status,\npass, clearance, and\npayment in one place.','OSP home empty hero body',true,now(),now()),
('ltk_home_hero_empty_traveler_label','home.hero.empty.travelerLabel','traveler','Traveler Access','OSP home empty traveler label',true,now(),now()),
('ltk_home_header_official_traveler_pass','home.header.officialTravelerPass','traveler','Official Traveler Pass','OSP home header pass label',true,now(),now()),
('ltk_home_header_language_aria','home.header.language.ariaLabel','traveler','Open language selector','OSP home language aria label',true,now(),now()),
('ltk_home_header_currency_aria','home.header.currency.ariaLabel','traveler','Open currency selector','OSP home currency aria label',true,now(),now()),
('ltk_home_header_assistant_aria','home.header.assistant.ariaLabel','traveler','Open OSP Travel Assistant','OSP home assistant aria label',true,now(),now()),
('ltk_home_header_notifications_aria','home.header.notifications.ariaLabel','traveler','Notifications','OSP home notifications aria label',true,now(),now()),
('ltk_home_pass_card_pass_code','home.passCard.passCode','traveler','Pass Code','OSP home pass card pass code label',true,now(),now()),
('ltk_home_pass_card_valid_dates','home.passCard.validDates','traveler','Valid Dates','OSP home pass card valid dates label',true,now(),now()),
('ltk_home_pass_card_badge_prefix','home.passCard.badgePrefix','traveler','PASS','OSP home pass card badge prefix',true,now(),now()),
('ltk_home_status_clearance','home.status.clearance','traveler','Clearance Status','OSP home clearance status label',true,now(),now()),
('ltk_home_status_payment','home.status.payment','traveler','Payment Status','OSP home payment status label',true,now(),now()),
('ltk_home_status_pass','home.status.pass','traveler','Pass Status','OSP home pass status label',true,now(),now()),
('ltk_home_status_trip_dates','home.status.tripDates','traveler','Trip Dates','OSP home trip dates label',true,now(),now()),
('ltk_home_reassurance_message','home.reassurance.message','traveler','Your pass, clearance, payment, and trip records stay connected to your One Siargao Pass profile.','OSP home reassurance message',true,now(),now()),
('ltk_home_journey_title','home.journey.title','traveler','Continue Your Journey','OSP home journey section title',true,now(),now()),
('ltk_home_journey_trips_title','home.journey.trips.title','traveler','Trips','OSP home trips journey title',true,now(),now()),
('ltk_home_journey_trips_subtitle','home.journey.trips.subtitle','traveler','Plans & records','OSP home trips journey subtitle',true,now(),now()),
('ltk_home_journey_payments_title','home.journey.payments.title','traveler','Payments','OSP home payments journey title',true,now(),now()),
('ltk_home_journey_payments_subtitle','home.journey.payments.subtitle','traveler','Status & receipts','OSP home payments journey subtitle',true,now(),now()),
('ltk_home_journey_passport_map_title','home.journey.passportMap.title','traveler','Passport Map','OSP home passport map journey title',true,now(),now()),
('ltk_home_journey_passport_map_subtitle','home.journey.passportMap.subtitle','traveler','Trails & stamps','OSP home passport map journey subtitle',true,now(),now()),
('ltk_home_journey_checkpoints_title','home.journey.checkpoints.title','traveler','Checkpoints','OSP home checkpoints journey title',true,now(),now()),
('ltk_home_journey_checkpoints_subtitle','home.journey.checkpoints.subtitle','traveler','QR & access state','OSP home checkpoints journey subtitle',true,now(),now()),
('ltk_home_bottom_nav_home','home.bottomNav.home','traveler','Home','OSP home bottom nav home label',true,now(),now()),
('ltk_home_bottom_nav_trips','home.bottomNav.trips','traveler','Trips','OSP home bottom nav trips label',true,now(),now()),
('ltk_home_bottom_nav_payments','home.bottomNav.payments','traveler','Payments','OSP home bottom nav payments label',true,now(),now()),
('ltk_home_bottom_nav_profile','home.bottomNav.profile','traveler','Profile','OSP home bottom nav profile label',true,now(),now()),
('ltk_home_pass_open_qr_aria','home.pass.openQr.ariaLabel','traveler','Open active pass QR','OSP home active pass QR aria label',true,now(),now()),
('ltk_settings_title','settings.title','traveler','Traveler Controls','Traveler settings screen title',true,now(),now()),
('ltk_settings_language_title','settings.language.title','traveler','Choose your travel language','Language settings title',true,now(),now()),
('ltk_trips_title','trips.title','traveler','My Trips','Traveler trips title',true,now(),now()),
('ltk_trips_back_home','trips.backHome','traveler','Back to Home','Trips back home label',true,now(),now()),
('ltk_trips_header_eyebrow','trips.header.eyebrow','traveler','Traveler Records','Trips header eyebrow',true,now(),now()),
('ltk_trips_header_body','trips.header.body','traveler','Review your registered trips, clearance state, and pass access.','Trips header body',true,now(),now()),
('ltk_trips_nav_home','trips.nav.home','traveler','Home','Trips nav home label',true,now(),now()),
('ltk_trips_nav_pass','trips.nav.pass','traveler','Traveler Pass','Trips nav pass label',true,now(),now()),
('ltk_trips_nav_logout','trips.nav.logout','traveler','Logout','Trips nav logout label',true,now(),now()),
('ltk_trips_load_error_title','trips.loadError.title','traveler','Trip Load Error','Trips load error title',true,now(),now()),
('ltk_trips_summary_title','trips.summary.title','traveler','Trip Summary','Trips summary title',true,now(),now()),
('ltk_trips_summary_visible','trips.summary.visible','traveler','Visible','Trips visible summary label',true,now(),now()),
('ltk_trips_summary_active','trips.summary.active','traveler','Active','Trips active summary label',true,now(),now()),
('ltk_trips_summary_passes','trips.summary.passes','traveler','Passes','Trips passes summary label',true,now(),now()),
('ltk_trips_preferred_label','trips.preferred.label','traveler','Preferred Traveler Trip','Trips preferred trip label',true,now(),now()),
('ltk_trips_preferred_fallback','trips.preferred.fallback','traveler','Current selected trip','Trips preferred fallback',true,now(),now()),
('ltk_trips_list_title','trips.list.title','traveler','My Trips','Trips list title',true,now(),now()),
('ltk_trips_empty_body','trips.empty.body','traveler','No trips found yet. Once you register or link a trip, it will appear here.','Trips empty body',true,now(),now()),
('ltk_trips_card_fallback_title','trips.card.fallbackTitle','traveler','Traveler Trip','Trips card fallback title',true,now(),now()),
('ltk_trips_card_current','trips.card.current','traveler','Current traveler trip','Trips card current label',true,now(),now()),
('ltk_trips_card_trip_status','trips.card.tripStatus','traveler','Trip Status','Trips card trip status label',true,now(),now()),
('ltk_trips_card_clearance','trips.card.clearance','traveler','Clearance','Trips card clearance label',true,now(),now()),
('ltk_trips_card_arrival','trips.card.arrival','traveler','Arrival','Trips card arrival label',true,now(),now()),
('ltk_trips_card_departure','trips.card.departure','traveler','Departure','Trips card departure label',true,now(),now()),
('ltk_trips_card_view_trip','trips.card.viewTrip','traveler','View Trip','Trips card view trip label',true,now(),now()),
('ltk_trips_card_open_pass','trips.card.openPass','traveler','Open Pass','Trips card open pass label',true,now(),now()),
('ltk_trip_detail_title','tripDetail.title','traveler','View Trip','Trip detail screen title',true,now(),now()),
('ltk_trip_detail_nav_back_to_trips','tripDetail.nav.backToTrips','traveler','Back to Trips','Trip detail back to trips label',true,now(),now()),
('ltk_trip_detail_nav_home','tripDetail.nav.home','traveler','Home','Trip detail nav home label',true,now(),now()),
('ltk_trip_detail_nav_pass','tripDetail.nav.pass','traveler','Pass','Trip detail nav pass label',true,now(),now()),
('ltk_trip_detail_nav_passport_map','tripDetail.nav.passportMap','traveler','Passport Map','Trip detail nav passport map label',true,now(),now()),
('ltk_trip_detail_nav_logout','tripDetail.nav.logout','traveler','Logout','Trip detail nav logout label',true,now(),now()),
('ltk_trip_detail_header_eyebrow','tripDetail.header.eyebrow','traveler','Trip Command Screen','Trip detail header eyebrow',true,now(),now()),
('ltk_trip_detail_header_body','tripDetail.header.body','traveler','Review your trip, clearance, booking, payment, and pass state.','Trip detail header body',true,now(),now()),
('ltk_trip_detail_hero_active_record','tripDetail.hero.activeRecord','traveler','Active Trip Record','Trip detail active record label',true,now(),now()),
('ltk_trip_detail_trip_fallback_title','tripDetail.tripFallbackTitle','traveler','Traveler Trip','Trip detail fallback trip title',true,now(),now()),
('ltk_trip_detail_load_error_title','tripDetail.loadError.title','traveler','Load Error','Trip detail load error title',true,now(),now()),
('ltk_trip_detail_core_status_title','tripDetail.coreStatus.title','traveler','Core Status','Trip detail core status title',true,now(),now()),
('ltk_trip_detail_core_status_trip','tripDetail.coreStatus.trip','traveler','Trip','Trip detail trip status label',true,now(),now()),
('ltk_trip_detail_core_status_clearance','tripDetail.coreStatus.clearance','traveler','Clearance','Trip detail clearance status label',true,now(),now()),
('ltk_trip_detail_core_status_manifest','tripDetail.coreStatus.manifest','traveler','Manifest','Trip detail manifest label',true,now(),now()),
('ltk_trip_detail_core_status_pass','tripDetail.coreStatus.pass','traveler','Pass','Trip detail pass label',true,now(),now()),
('ltk_trip_detail_status_listed','tripDetail.status.listed','traveler','Listed','Trip detail listed status label',true,now(),now()),
('ltk_trip_detail_status_not_listed','tripDetail.status.notListed','traveler','Not Listed','Trip detail not listed status label',true,now(),now()),
('ltk_trip_detail_status_not_issued','tripDetail.status.notIssued','traveler','Not Issued','Trip detail not issued status label',true,now(),now()),
('ltk_trip_detail_details_title','tripDetail.details.title','traveler','Trip Details','Trip detail details section title',true,now(),now()),
('ltk_trip_detail_details_arrival','tripDetail.details.arrival','traveler','Arrival','Trip detail arrival label',true,now(),now()),
('ltk_trip_detail_details_departure','tripDetail.details.departure','traveler','Departure','Trip detail departure label',true,now(),now()),
('ltk_trip_detail_details_origin','tripDetail.details.origin','traveler','Origin','Trip detail origin label',true,now(),now()),
('ltk_trip_detail_details_accommodation','tripDetail.details.accommodation','traveler','Accommodation','Trip detail accommodation label',true,now(),now()),
('ltk_trip_detail_members_title','tripDetail.members.title','traveler','Trip Members','Trip detail members title',true,now(),now()),
('ltk_trip_detail_members_fallback_name','tripDetail.members.fallbackName','traveler','Trip Member','Trip detail member fallback name',true,now(),now()),
('ltk_trip_detail_members_type','tripDetail.members.type','traveler','Type','Trip detail member type label',true,now(),now()),
('ltk_trip_detail_members_nationality','tripDetail.members.nationality','traveler','Nationality','Trip detail member nationality label',true,now(),now()),
('ltk_trip_detail_members_age','tripDetail.members.age','traveler','Age','Trip detail member age label',true,now(),now()),
('ltk_trip_detail_members_primary','tripDetail.members.primary','traveler','Primary','Trip detail member primary label',true,now(),now()),
('ltk_trip_detail_members_yes','tripDetail.members.yes','traveler','Yes','Trip detail yes label',true,now(),now()),
('ltk_trip_detail_members_no','tripDetail.members.no','traveler','No','Trip detail no label',true,now(),now()),
('ltk_trip_detail_members_empty','tripDetail.members.empty','traveler','No trip members yet.','Trip detail members empty copy',true,now(),now()),
('ltk_trip_detail_companion_title','tripDetail.companion.title','traveler','Add Companion','Trip detail add companion title',true,now(),now()),
('ltk_trip_detail_companion_full_name_placeholder','tripDetail.companion.fullNamePlaceholder','traveler','Companion full name','Trip detail companion full name placeholder',true,now(),now()),
('ltk_trip_detail_companion_nationality_placeholder','tripDetail.companion.nationalityPlaceholder','traveler','PH','Trip detail companion nationality placeholder',true,now(),now()),
('ltk_trip_detail_companion_age_placeholder','tripDetail.companion.agePlaceholder','traveler','Age','Trip detail companion age placeholder',true,now(),now()),
('ltk_trip_detail_companion_passport_placeholder','tripDetail.companion.passportPlaceholder','traveler','Passport / ID hint','Trip detail companion passport placeholder',true,now(),now()),
('ltk_trip_detail_companion_submit','tripDetail.companion.submit','traveler','Add Companion','Trip detail add companion submit',true,now(),now()),
('ltk_trip_detail_booking_summary_title','tripDetail.bookingSummary.title','traveler','Booking Summary','Trip detail booking summary title',true,now(),now()),
('ltk_trip_detail_booking_summary_total','tripDetail.bookingSummary.total','traveler','Total','Trip detail booking total label',true,now(),now()),
('ltk_trip_detail_booking_summary_paid','tripDetail.bookingSummary.paid','traveler','Paid','Trip detail booking paid label',true,now(),now()),
('ltk_trip_detail_booking_summary_unpaid','tripDetail.bookingSummary.unpaid','traveler','Unpaid','Trip detail booking unpaid label',true,now(),now()),
('ltk_trip_detail_booking_summary_latest_ref','tripDetail.bookingSummary.latestRef','traveler','Latest Ref','Trip detail booking latest ref label',true,now(),now()),
('ltk_trip_detail_current_booking_title','tripDetail.currentBooking.title','traveler','Current Booking','Trip detail current booking title',true,now(),now()),
('ltk_trip_detail_current_booking_reference','tripDetail.currentBooking.reference','traveler','Booking Reference','Trip detail booking reference label',true,now(),now()),
('ltk_trip_detail_current_booking_status','tripDetail.currentBooking.status','traveler','Booking Status','Trip detail booking status label',true,now(),now()),
('ltk_trip_detail_current_booking_total','tripDetail.currentBooking.total','traveler','Booking Total','Trip detail booking total amount label',true,now(),now()),
('ltk_trip_detail_current_booking_currency','tripDetail.currentBooking.currency','traveler','Currency','Trip detail currency label',true,now(),now()),
('ltk_trip_detail_payment_status_title','tripDetail.paymentStatus.title','traveler','Payment Status','Trip detail payment status title',true,now(),now()),
('ltk_trip_detail_payment_status_state','tripDetail.paymentStatus.state','traveler','State','Trip detail payment state label',true,now(),now()),
('ltk_trip_detail_payment_status_paid','tripDetail.paymentStatus.paid','traveler','Paid','Trip detail payment paid label',true,now(),now()),
('ltk_trip_detail_payment_status_unpaid','tripDetail.paymentStatus.unpaid','traveler','Unpaid','Trip detail payment unpaid label',true,now(),now()),
('ltk_trip_detail_payment_status_intent','tripDetail.paymentStatus.intent','traveler','Intent','Trip detail payment intent label',true,now(),now()),
('ltk_trip_detail_payment_actions_title','tripDetail.paymentActions.title','traveler','Payment Actions','Trip detail payment actions title',true,now(),now()),
('ltk_trip_detail_payment_actions_no_booking','tripDetail.paymentActions.noBooking','traveler','No current booking is linked to this trip yet, so payment actions are unavailable.','Trip detail no booking payment actions copy',true,now(),now()),
('ltk_trip_detail_payment_actions_create','tripDetail.paymentActions.create','traveler','Create Payment','Trip detail create payment button',true,now(),now()),
('ltk_trip_detail_payment_actions_confirm','tripDetail.paymentActions.confirm','traveler','Confirm Payment','Trip detail confirm payment button',true,now(),now()),
('ltk_trip_detail_payment_actions_detail','tripDetail.paymentActions.detail','traveler','Payment Detail','Trip detail payment detail link',true,now(),now()),
('ltk_trip_detail_pass_access_title','tripDetail.passAccess.title','traveler','Pass Access','Trip detail pass access title',true,now(),now()),
('ltk_trip_detail_pass_access_pass_code','tripDetail.passAccess.passCode','traveler','Pass Code','Trip detail pass code label',true,now(),now()),
('ltk_trip_detail_pass_access_pass_status','tripDetail.passAccess.passStatus','traveler','Pass Status','Trip detail pass status label',true,now(),now()),
('ltk_trip_detail_pass_access_qr_version','tripDetail.passAccess.qrVersion','traveler','QR Version','Trip detail QR version label',true,now(),now()),
('ltk_trip_detail_pass_access_open_pass','tripDetail.passAccess.openPass','traveler','Open Pass','Trip detail open pass link',true,now(),now()),
('ltk_trip_detail_pass_access_passport_map','tripDetail.passAccess.passportMap','traveler','Passport Map','Trip detail passport map link',true,now(),now()),
('ltk_trip_detail_payment_history_title','tripDetail.paymentHistory.title','traveler','Payment History','Trip detail payment history title',true,now(),now()),
('ltk_trip_detail_payment_history_booking_reference','tripDetail.paymentHistory.bookingReference','traveler','Booking Reference','Trip detail payment history booking reference label',true,now(),now()),
('ltk_trip_detail_payment_history_booking_status','tripDetail.paymentHistory.bookingStatus','traveler','Booking Status','Trip detail payment history booking status label',true,now(),now()),
('ltk_trip_detail_payment_history_payment_state','tripDetail.paymentHistory.paymentState','traveler','Payment State','Trip detail payment history payment state label',true,now(),now()),
('ltk_trip_detail_payment_history_latest_intent','tripDetail.paymentHistory.latestIntent','traveler','Latest Intent','Trip detail payment history latest intent label',true,now(),now()),
('ltk_trip_detail_technical_title','tripDetail.technical.title','traveler','Technical Record','Trip detail technical record title',true,now(),now()),
('ltk_trip_detail_technical_trip_id','tripDetail.technical.tripId','traveler','Trip ID','Trip detail technical trip ID label',true,now(),now()),
('ltk_trip_detail_technical_manifest_ref','tripDetail.technical.manifestRef','traveler','Manifest Ref','Trip detail technical manifest ref label',true,now(),now()),
('ltk_trip_detail_technical_booking_id','tripDetail.technical.bookingId','traveler','Booking ID','Trip detail technical booking ID label',true,now(),now()),
('ltk_trip_detail_technical_payment_intent_id','tripDetail.technical.paymentIntentId','traveler','Payment Intent ID','Trip detail technical payment intent ID label',true,now(),now()),
('ltk_payment_detail_title','paymentDetail.title','traveler','Payment Detail','Payment detail screen title',true,now(),now()),
('ltk_payment_detail_nav_back_to_trips','paymentDetail.nav.backToTrips','traveler','Back to Trips','Payment detail back to trips label',true,now(),now()),
('ltk_payment_detail_nav_home','paymentDetail.nav.home','traveler','Home','Payment detail home nav label',true,now(),now()),
('ltk_payment_detail_nav_my_trips','paymentDetail.nav.myTrips','traveler','My Trips','Payment detail my trips nav label',true,now(),now()),
('ltk_payment_detail_nav_logout','paymentDetail.nav.logout','traveler','Logout','Payment detail logout nav label',true,now(),now()),
('ltk_payment_detail_header_eyebrow','paymentDetail.header.eyebrow','traveler','Payment Record','Payment detail header eyebrow',true,now(),now()),
('ltk_payment_detail_header_body','paymentDetail.header.body','traveler','Review payment state, booking linkage, and receipt information.','Payment detail header body',true,now(),now()),
('ltk_payment_detail_status_verified','paymentDetail.status.verified','traveler','Payment Verified','Payment detail verified status label',true,now(),now()),
('ltk_payment_detail_status_pending','paymentDetail.status.pending','traveler','Payment Pending','Payment detail pending status label',true,now(),now()),
('ltk_payment_detail_status_attention','paymentDetail.status.attention','traveler','Payment Attention Needed','Payment detail attention status label',true,now(),now()),
('ltk_payment_detail_status_record','paymentDetail.status.record','traveler','Payment Record','Payment detail record status label',true,now(),now()),
('ltk_payment_detail_status_fallback','paymentDetail.status.fallback','traveler','Record','Payment detail status fallback',true,now(),now()),
('ltk_payment_detail_intent_fallback','paymentDetail.intentFallback','traveler','Payment intent record','Payment detail intent fallback',true,now(),now()),
('ltk_payment_detail_load_error_title','paymentDetail.loadError.title','traveler','Load Error','Payment detail load error title',true,now(),now()),
('ltk_payment_detail_receipt_title','paymentDetail.receipt.title','traveler','Receipt Summary','Payment detail receipt title',true,now(),now()),
('ltk_payment_detail_receipt_amount','paymentDetail.receipt.amount','traveler','Amount','Payment detail amount label',true,now(),now()),
('ltk_payment_detail_receipt_currency','paymentDetail.receipt.currency','traveler','Currency','Payment detail currency label',true,now(),now()),
('ltk_payment_detail_receipt_status','paymentDetail.receipt.status','traveler','Status','Payment detail status label',true,now(),now()),
('ltk_payment_detail_receipt_provider','paymentDetail.receipt.provider','traveler','Provider','Payment detail provider label',true,now(),now()),
('ltk_payment_detail_fx_display_estimate','paymentDetail.fx.displayEstimate','traveler','Display Estimate','Payment detail FX display estimate label',true,now(),now()),
('ltk_payment_detail_fx_rate','paymentDetail.fx.rate','traveler','FX Rate','Payment detail FX rate label',true,now(),now()),
('ltk_payment_detail_fx_source','paymentDetail.fx.source','traveler','FX Source','Payment detail FX source label',true,now(),now()),
('ltk_payment_detail_fx_as_of','paymentDetail.fx.asOf','traveler','Rate As Of','Payment detail FX rate timestamp label',true,now(),now()),
('ltk_payment_detail_fx_note','paymentDetail.fx.note','traveler','FX is shown as a traveler display estimate only. PHP remains the payment and settlement source of truth.','Payment detail FX display-only note',true,now(),now()),
('ltk_payment_detail_state_title','paymentDetail.state.title','traveler','Payment State','Payment detail payment state title',true,now(),now()),
('ltk_payment_detail_state_state','paymentDetail.state.state','traveler','State','Payment detail state label',true,now(),now()),
('ltk_payment_detail_state_paid','paymentDetail.state.paid','traveler','Paid','Payment detail paid label',true,now(),now()),
('ltk_payment_detail_state_unpaid','paymentDetail.state.unpaid','traveler','Unpaid','Payment detail unpaid label',true,now(),now()),
('ltk_payment_detail_state_updated','paymentDetail.state.updated','traveler','Updated','Payment detail updated label',true,now(),now()),
('ltk_payment_detail_booking_title','paymentDetail.booking.title','traveler','Booking Linkage','Payment detail booking linkage title',true,now(),now()),
('ltk_payment_detail_booking_booking_id','paymentDetail.booking.bookingId','traveler','Booking ID','Payment detail booking ID label',true,now(),now()),
('ltk_payment_detail_booking_intent_reference','paymentDetail.booking.intentReference','traveler','Intent Reference','Payment detail intent reference label',true,now(),now()),
('ltk_payment_detail_booking_payment_intent_id','paymentDetail.booking.paymentIntentId','traveler','Payment Intent ID','Payment detail payment intent ID label',true,now(),now()),
('ltk_payment_detail_booking_last_payment_intent','paymentDetail.booking.lastPaymentIntent','traveler','Last Payment Intent','Payment detail last payment intent label',true,now(),now()),
('ltk_payment_detail_timeline_title','paymentDetail.timeline.title','traveler','Timeline','Payment detail timeline title',true,now(),now()),
('ltk_payment_detail_timeline_confirmed_at','paymentDetail.timeline.confirmedAt','traveler','Confirmed At','Payment detail confirmed at label',true,now(),now()),
('ltk_payment_detail_timeline_created_at','paymentDetail.timeline.createdAt','traveler','Created At','Payment detail created at label',true,now(),now()),
('ltk_payment_detail_timeline_updated_at','paymentDetail.timeline.updatedAt','traveler','Updated At','Payment detail updated at label',true,now(),now()),
('ltk_payment_detail_actions_title','paymentDetail.actions.title','traveler','Next Actions','Payment detail next actions title',true,now(),now()),
('ltk_payment_detail_actions_note','paymentDetail.actions.note','traveler','Payments are linked to your OSP booking and pass status. Operational changes must come from verified backend records.','Payment detail next actions note',true,now(),now()),
('ltk_spm_title','spm.title','traveler','Your Siargao Journey, Mapped','SPM hero title',true,now(),now()),
('ltk_pass_header_eyebrow','pass.header.eyebrow','traveler','Official Traveler Pass','Traveler pass header eyebrow',true,now(),now()),
('ltk_pass_header_title','pass.header.title','traveler','OSP Pass','Traveler pass header title',true,now(),now()),
('ltk_pass_header_body','pass.header.body','traveler','View your issued pass, QR credential, trip status, and Passport Map bridge.','Traveler pass header body',true,now(),now()),
('ltk_pass_nav_home','pass.nav.home','traveler','Home','Traveler pass nav home label',true,now(),now()),
('ltk_pass_nav_my_trips','pass.nav.myTrips','traveler','My Trips','Traveler pass nav trips label',true,now(),now()),
('ltk_pass_nav_passport_map','pass.nav.passportMap','traveler','Passport Map','Traveler pass nav passport map label',true,now(),now()),
('ltk_pass_nav_logout','pass.nav.logout','traveler','Logout','Traveler pass nav logout label',true,now(),now()),
('ltk_pass_access_note_title','pass.accessNote.title','traveler','Pass Access Note','Traveler pass access note title',true,now(),now()),
('ltk_pass_access_note_body1','pass.accessNote.body1','traveler','This page uses the authenticated session to load the traveler pass view.','Traveler pass access note body 1',true,now(),now()),
('ltk_pass_access_note_body2','pass.accessNote.body2','traveler','If an issued pass already exists, it is prioritized. Otherwise the latest traveler trip is checked for pass eligibility.','Traveler pass access note body 2',true,now(),now()),
('ltk_pass_load_error_title','pass.loadError.title','traveler','Load Error','Traveler pass load error title',true,now(),now()),
('ltk_pass_empty_title','pass.empty.title','traveler','No Trips Available','Traveler pass empty title',true,now(),now()),
('ltk_pass_empty_body','pass.empty.body','traveler','No traveler trip is available yet for pass viewing.','Traveler pass empty body',true,now(),now()),
('ltk_pass_readiness_section_title','pass.readiness.sectionTitle','traveler','Pass Readiness','Traveler pass readiness section title',true,now(),now()),
('ltk_pass_readiness_no_trip_title','pass.readiness.noTrip.title','traveler','No Trip Available','Traveler pass no trip title',true,now(),now()),
('ltk_pass_readiness_no_trip_body','pass.readiness.noTrip.body','traveler','No traveler trip is available yet for pass viewing.','Traveler pass no trip body',true,now(),now()),
('ltk_pass_readiness_ready_title','pass.readiness.ready.title','traveler','Pass Ready','Traveler pass ready title',true,now(),now()),
('ltk_pass_readiness_ready_body','pass.readiness.ready.body','traveler','Your pass is on file and ready for operational use.','Traveler pass ready body',true,now(),now()),
('ltk_pass_readiness_on_record_title','pass.readiness.onRecord.title','traveler','Pass On Record','Traveler pass on record title',true,now(),now()),
('ltk_pass_readiness_pending_title','pass.readiness.pending.title','traveler','Pass Pending','Traveler pass pending title',true,now(),now()),
('ltk_pass_readiness_pending_body','pass.readiness.pending.body','traveler','Your traveler pass is not yet available. Check the status summary below for the next requirement.','Traveler pass pending body',true,now(),now()),
('ltk_pass_qr_section_title','pass.qr.sectionTitle','traveler','QR Credential','Traveler pass QR section title',true,now(),now()),
('ltk_pass_qr_active_label','pass.qr.activeLabel','traveler','Active Pass QR Credential','Traveler pass QR active label',true,now(),now()),
('ltk_pass_qr_not_ready','pass.qr.notReady','traveler','QR is on record but not ready for operational use yet.','Traveler pass QR not ready message',true,now(),now()),
('ltk_pass_qr_unavailable','pass.qr.unavailable','traveler','QR token is not available for this pass yet.','Traveler pass QR unavailable message',true,now(),now()),
('ltk_pass_action_required_title','pass.actionRequired.title','traveler','Action Required','Traveler pass action required title',true,now(),now()),
('ltk_pass_blocked_title','pass.blocked.title','traveler','Pass Blocked','Traveler pass blocked title',true,now(),now()),
('ltk_pass_spm_section_title','pass.spm.sectionTitle','traveler','Siargao Passport Map','Traveler pass SPM section title',true,now(),now()),
('ltk_pass_spm_eyebrow','pass.spm.eyebrow','traveler','Second Screen','Traveler pass SPM eyebrow',true,now(),now()),
('ltk_pass_spm_title','pass.spm.title','traveler','Continue to your Passport Map','Traveler pass SPM title',true,now(),now()),
('ltk_pass_spm_body','pass.spm.body','traveler','Your SPM trail progress uses governed OSP QR, stamp, pass, and trip records when available. Preview layout cards may appear only to preserve the approved map geometry.','Traveler pass SPM body',true,now(),now()),
('ltk_pass_spm_cta','pass.spm.cta','traveler','Open Siargao Passport Map','Traveler pass SPM CTA',true,now(),now()),
('ltk_pass_status_section_title','pass.status.sectionTitle','traveler','Key Status Summary','Traveler pass status section title',true,now(),now())
on conflict ("key") do update set
"scope"=excluded."scope",
"defaultText"=excluded."defaultText",
"description"=excluded."description",
"isActive"=excluded."isActive",
"updatedAt"=now();

insert into "LanguageTranslationValue" ("id","languagePackId","translationKeyId","value","status","createdAt","updatedAt")
select replace('ltv_' || lp."languageCode" || '_' || tk."id", '-', '_'), lp."id", tk."id", tk."defaultText", 'PUBLISHED', now(), now()
from "LanguagePack" lp
cross join "LanguageTranslationKey" tk
where lp."languageCode" = 'en'
on conflict ("languagePackId","translationKeyId") do update set
"value"=excluded."value",
"status"='PUBLISHED',
"updatedAt"=now();

insert into "LanguageTranslationValue" ("id","languagePackId","translationKeyId","value","status","createdAt","updatedAt") values
('ltv_fil_ltk_settings_title','lang_fil','ltk_settings_title','Mga Kontrol ng Traveler','PUBLISHED',now(),now()),
('ltv_fil_ltk_settings_language_title','lang_fil','ltk_settings_language_title','Piliin ang travel language mo','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_title','lang_fil','ltk_home_title','Trip Aktibo. Pass Handa.','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_show_qr','lang_fil','ltk_home_show_qr','Ipakita ang QR','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_passport_map','lang_fil','ltk_home_passport_map','Buksan ang Passport Map','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_hero_active_title','lang_fil','ltk_home_hero_active_title','Trip Aktibo.\nPass Handa.','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_hero_active_body','lang_fil','ltk_home_hero_active_body','Tingnan ang trip status,\npass, clearance, at\npayment mo sa isang lugar.','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_hero_active_traveler_label','lang_fil','ltk_home_hero_active_traveler_label','Verified Traveler','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_header_official_traveler_pass','lang_fil','ltk_home_header_official_traveler_pass','Official Traveler Pass','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_header_language_aria','lang_fil','ltk_home_header_language_aria','Buksan ang language selector','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_header_currency_aria','lang_fil','ltk_home_header_currency_aria','Buksan ang currency selector','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_header_assistant_aria','lang_fil','ltk_home_header_assistant_aria','Buksan ang OSP Travel Assistant','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_header_notifications_aria','lang_fil','ltk_home_header_notifications_aria','Mga notification','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_pass_card_pass_code','lang_fil','ltk_home_pass_card_pass_code','Pass Code','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_pass_card_valid_dates','lang_fil','ltk_home_pass_card_valid_dates','Valid Dates','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_pass_card_badge_prefix','lang_fil','ltk_home_pass_card_badge_prefix','PASS','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_status_clearance','lang_fil','ltk_home_status_clearance','Clearance Status','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_status_payment','lang_fil','ltk_home_status_payment','Payment Status','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_status_pass','lang_fil','ltk_home_status_pass','Pass Status','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_status_trip_dates','lang_fil','ltk_home_status_trip_dates','Trip Dates','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_reassurance_message','lang_fil','ltk_home_reassurance_message','Nakakonekta ang pass, clearance, payment, at trip records mo sa One Siargao Pass profile mo.','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_title','lang_fil','ltk_home_journey_title','Ipagpatuloy ang Journey Mo','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_trips_title','lang_fil','ltk_home_journey_trips_title','Trips','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_trips_subtitle','lang_fil','ltk_home_journey_trips_subtitle','Plans & records','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_payments_title','lang_fil','ltk_home_journey_payments_title','Payments','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_payments_subtitle','lang_fil','ltk_home_journey_payments_subtitle','Status & receipts','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_passport_map_title','lang_fil','ltk_home_journey_passport_map_title','Passport Map','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_passport_map_subtitle','lang_fil','ltk_home_journey_passport_map_subtitle','Trails & stamps','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_checkpoints_title','lang_fil','ltk_home_journey_checkpoints_title','Checkpoints','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_journey_checkpoints_subtitle','lang_fil','ltk_home_journey_checkpoints_subtitle','QR & access state','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_bottom_nav_home','lang_fil','ltk_home_bottom_nav_home','Home','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_bottom_nav_trips','lang_fil','ltk_home_bottom_nav_trips','Trips','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_bottom_nav_payments','lang_fil','ltk_home_bottom_nav_payments','Payments','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_bottom_nav_profile','lang_fil','ltk_home_bottom_nav_profile','Profile','PUBLISHED',now(),now()),
('ltv_fil_ltk_home_pass_open_qr_aria','lang_fil','ltk_home_pass_open_qr_aria','Buksan ang active pass QR','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_header_eyebrow','lang_fil','ltk_pass_header_eyebrow','Official Traveler Pass','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_header_title','lang_fil','ltk_pass_header_title','OSP Pass','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_header_body','lang_fil','ltk_pass_header_body','Tingnan ang issued pass, QR credential, trip status, at Passport Map bridge mo.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_nav_home','lang_fil','ltk_pass_nav_home','Home','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_nav_my_trips','lang_fil','ltk_pass_nav_my_trips','My Trips','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_nav_passport_map','lang_fil','ltk_pass_nav_passport_map','Passport Map','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_nav_logout','lang_fil','ltk_pass_nav_logout','Logout','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_access_note_title','lang_fil','ltk_pass_access_note_title','Pass Access Note','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_access_note_body1','lang_fil','ltk_pass_access_note_body1','Ginagamit ng page na ito ang authenticated session para i-load ang traveler pass view.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_access_note_body2','lang_fil','ltk_pass_access_note_body2','Kung may issued pass na, iyon ang uunahin. Kung wala pa, iche-check ang latest traveler trip para sa pass eligibility.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_empty_title','lang_fil','ltk_pass_empty_title','Walang Trips Available','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_empty_body','lang_fil','ltk_pass_empty_body','Wala pang traveler trip na available para sa pass viewing.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_readiness_section_title','lang_fil','ltk_pass_readiness_section_title','Pass Readiness','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_readiness_ready_title','lang_fil','ltk_pass_readiness_ready_title','Pass Ready','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_readiness_ready_body','lang_fil','ltk_pass_readiness_ready_body','Naka-record na ang pass mo at ready na para sa operational use.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_readiness_pending_title','lang_fil','ltk_pass_readiness_pending_title','Pass Pending','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_readiness_pending_body','lang_fil','ltk_pass_readiness_pending_body','Hindi pa available ang traveler pass mo. Tingnan ang status summary para sa susunod na requirement.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_qr_section_title','lang_fil','ltk_pass_qr_section_title','QR Credential','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_qr_active_label','lang_fil','ltk_pass_qr_active_label','Active Pass QR Credential','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_qr_not_ready','lang_fil','ltk_pass_qr_not_ready','Naka-record ang QR pero hindi pa ready para sa operational use.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_qr_unavailable','lang_fil','ltk_pass_qr_unavailable','Wala pang QR token para sa pass na ito.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_action_required_title','lang_fil','ltk_pass_action_required_title','Action Required','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_blocked_title','lang_fil','ltk_pass_blocked_title','Pass Blocked','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_spm_section_title','lang_fil','ltk_pass_spm_section_title','Siargao Passport Map','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_spm_eyebrow','lang_fil','ltk_pass_spm_eyebrow','Second Screen','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_spm_title','lang_fil','ltk_pass_spm_title','Magpatuloy sa Passport Map mo','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_spm_body','lang_fil','ltk_pass_spm_body','Ang SPM trail progress mo ay gumagamit ng governed OSP QR, stamp, pass, at trip records kapag available. Preview layout cards ay para mapanatili lang ang approved map geometry.','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_spm_cta','lang_fil','ltk_pass_spm_cta','Buksan ang Siargao Passport Map','PUBLISHED',now(),now()),
('ltv_fil_ltk_pass_status_section_title','lang_fil','ltk_pass_status_section_title','Key Status Summary','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_back_home','lang_fil','ltk_trips_back_home','Bumalik sa Home','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_header_eyebrow','lang_fil','ltk_trips_header_eyebrow','Traveler Records','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_header_body','lang_fil','ltk_trips_header_body','Tingnan ang registered trips, clearance state, at pass access mo.','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_nav_home','lang_fil','ltk_trips_nav_home','Home','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_nav_pass','lang_fil','ltk_trips_nav_pass','Traveler Pass','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_nav_logout','lang_fil','ltk_trips_nav_logout','Logout','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_summary_title','lang_fil','ltk_trips_summary_title','Trip Summary','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_summary_visible','lang_fil','ltk_trips_summary_visible','Visible','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_summary_active','lang_fil','ltk_trips_summary_active','Active','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_summary_passes','lang_fil','ltk_trips_summary_passes','Passes','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_preferred_label','lang_fil','ltk_trips_preferred_label','Preferred Traveler Trip','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_preferred_fallback','lang_fil','ltk_trips_preferred_fallback','Current selected trip','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_empty_body','lang_fil','ltk_trips_empty_body','Wala pang trips. Kapag nag-register o nag-link ka ng trip, lalabas ito dito.','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_card_current','lang_fil','ltk_trips_card_current','Current traveler trip','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_card_trip_status','lang_fil','ltk_trips_card_trip_status','Trip Status','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_card_clearance','lang_fil','ltk_trips_card_clearance','Clearance','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_card_arrival','lang_fil','ltk_trips_card_arrival','Arrival','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_card_departure','lang_fil','ltk_trips_card_departure','Departure','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_card_view_trip','lang_fil','ltk_trips_card_view_trip','View Trip','PUBLISHED',now(),now()),
('ltv_fil_ltk_trips_card_open_pass','lang_fil','ltk_trips_card_open_pass','Open Pass','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_nav_back_to_trips','lang_fil','ltk_trip_detail_nav_back_to_trips','Bumalik sa Trips','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_header_eyebrow','lang_fil','ltk_trip_detail_header_eyebrow','Trip Command Screen','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_header_body','lang_fil','ltk_trip_detail_header_body','Tingnan ang trip, clearance, booking, payment, at pass state mo.','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_core_status_title','lang_fil','ltk_trip_detail_core_status_title','Core Status','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_details_title','lang_fil','ltk_trip_detail_details_title','Trip Details','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_members_title','lang_fil','ltk_trip_detail_members_title','Trip Members','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_members_empty','lang_fil','ltk_trip_detail_members_empty','Wala pang trip members.','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_companion_title','lang_fil','ltk_trip_detail_companion_title','Magdagdag ng Companion','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_companion_full_name_placeholder','lang_fil','ltk_trip_detail_companion_full_name_placeholder','Buong pangalan ng companion','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_companion_passport_placeholder','lang_fil','ltk_trip_detail_companion_passport_placeholder','Passport / ID hint','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_companion_submit','lang_fil','ltk_trip_detail_companion_submit','Magdagdag ng Companion','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_booking_summary_title','lang_fil','ltk_trip_detail_booking_summary_title','Booking Summary','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_current_booking_title','lang_fil','ltk_trip_detail_current_booking_title','Current Booking','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_payment_status_title','lang_fil','ltk_trip_detail_payment_status_title','Payment Status','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_payment_actions_title','lang_fil','ltk_trip_detail_payment_actions_title','Payment Actions','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_payment_actions_no_booking','lang_fil','ltk_trip_detail_payment_actions_no_booking','Wala pang current booking na naka-link sa trip na ito, kaya hindi pa available ang payment actions.','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_payment_actions_create','lang_fil','ltk_trip_detail_payment_actions_create','Gumawa ng Payment','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_payment_actions_confirm','lang_fil','ltk_trip_detail_payment_actions_confirm','I-confirm ang Payment','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_payment_actions_detail','lang_fil','ltk_trip_detail_payment_actions_detail','Payment Detail','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_pass_access_title','lang_fil','ltk_trip_detail_pass_access_title','Pass Access','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_pass_access_open_pass','lang_fil','ltk_trip_detail_pass_access_open_pass','Buksan ang Pass','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_payment_history_title','lang_fil','ltk_trip_detail_payment_history_title','Payment History','PUBLISHED',now(),now()),
('ltv_fil_ltk_trip_detail_technical_title','lang_fil','ltk_trip_detail_technical_title','Technical Record','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_nav_back_to_trips','lang_fil','ltk_payment_detail_nav_back_to_trips','Bumalik sa Trips','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_header_eyebrow','lang_fil','ltk_payment_detail_header_eyebrow','Payment Record','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_header_body','lang_fil','ltk_payment_detail_header_body','Tingnan ang payment state, booking linkage, at receipt information.','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_receipt_title','lang_fil','ltk_payment_detail_receipt_title','Receipt Summary','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_state_title','lang_fil','ltk_payment_detail_state_title','Payment State','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_booking_title','lang_fil','ltk_payment_detail_booking_title','Booking Linkage','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_actions_title','lang_fil','ltk_payment_detail_actions_title','Next Actions','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_actions_note','lang_fil','ltk_payment_detail_actions_note','Nakakonekta ang payments sa OSP booking at pass status mo. Ang operational changes ay dapat manggaling sa verified backend records.','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_fx_display_estimate','lang_fil','ltk_payment_detail_fx_display_estimate','Display Estimate','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_fx_rate','lang_fil','ltk_payment_detail_fx_rate','FX Rate','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_fx_source','lang_fil','ltk_payment_detail_fx_source','FX Source','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_fx_as_of','lang_fil','ltk_payment_detail_fx_as_of','Rate As Of','PUBLISHED',now(),now()),
('ltv_fil_ltk_payment_detail_fx_note','lang_fil','ltk_payment_detail_fx_note','Ang FX ay traveler display estimate lamang. PHP pa rin ang payment at settlement source of truth.','PUBLISHED',now(),now())
on conflict ("languagePackId","translationKeyId") do update set
"value"=excluded."value",
"status"='PUBLISHED',
"updatedAt"=now();
