import { Module } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import {
  AccommodationVoucherDocumentsController,
  AccommodationVoucherEmailsController,
  AccommodationVoucherQrController,
  AdminAccommodationImportsController,
  AdminAccommodationVouchersController,
  AdminAccommodationsController,
  OperatorAccommodationRequestsController,
  OperatorAccommodationVouchersController,
  OperatorAccommodationsController,
  TravelerAccommodationRequestsController,
  TravelerAccommodationVouchersController,
  TravelerAccommodationsController,
} from './controllers';
import {
  AccommodationBookingRequestService,
  AccommodationCommercialSnapshotService,
  AccommodationExposureService,
  AccommodationInventoryService,
  AccommodationPayoutService,
  AccommodationProfileService,
  AccommodationStayService,
  AccommodationVoucherDocumentService,
  AccommodationVoucherEmailService,
  AccommodationVoucherQrService,
  AccommodationVoucherService,
  RawAccommodationImportService,
} from './services';

@Module({
  controllers: [
    TravelerAccommodationsController,
    TravelerAccommodationRequestsController,
    TravelerAccommodationVouchersController,
    OperatorAccommodationsController,
    OperatorAccommodationRequestsController,
    OperatorAccommodationVouchersController,
    AdminAccommodationsController,
    AdminAccommodationImportsController,
    AdminAccommodationVouchersController,
    AccommodationVoucherDocumentsController,
    AccommodationVoucherEmailsController,
    AccommodationVoucherQrController,
  ],
  providers: [
    PrismaService,
    AccommodationProfileService,
    AccommodationInventoryService,
    AccommodationBookingRequestService,
    AccommodationStayService,
    AccommodationCommercialSnapshotService,
    AccommodationPayoutService,
    AccommodationVoucherService,
    AccommodationVoucherDocumentService,
    AccommodationVoucherEmailService,
    AccommodationVoucherQrService,
    AccommodationExposureService,
    RawAccommodationImportService,
  ],
  exports: [
    AccommodationProfileService,
    AccommodationInventoryService,
    AccommodationBookingRequestService,
    AccommodationStayService,
    AccommodationCommercialSnapshotService,
    AccommodationPayoutService,
    AccommodationVoucherService,
    AccommodationVoucherDocumentService,
    AccommodationVoucherEmailService,
    AccommodationVoucherQrService,
    AccommodationExposureService,
    RawAccommodationImportService,
  ],
})
export class AccommodationsModule {}
