export type ControlTowerNavItem = {
  code: string;
  key: string;
  label: string;
  href: string;
  purpose: string;
  readiness: "Shell Ready" | "Gate Pending" | "Migration Pending";
  risk: string;
};

export const controlTowerNav: ControlTowerNavItem[] = [
  {
    code: "A",
    key: "command-center",
    label: "Command Center",
    href: "/admin/control-tower/command-center",
    purpose: "Executive operating overview for platform health, commercial readiness, QR events, approvals, warnings, and blockers.",
    readiness: "Shell Ready",
    risk: "Must not become a developer status dump.",
  },
  {
    code: "B",
    key: "osp-core",
    label: "OSP Core",
    href: "/admin/control-tower/osp-core",
    purpose: "Traveler identity, QR, OSP Passes, trips, auth routing, profile readiness, app settings, notifications, and safety.",
    readiness: "Gate Pending",
    risk: "Traveler identity and trip readiness cannot drift across random pages.",
  },
  {
    code: "C",
    key: "spm",
    label: "SPM / Passport Trails",
    href: "/admin/control-tower/spm",
    purpose: "Siargao Passport Map, official trails, curated tours, partner tours, DIY trails, stamps, and trail progress.",
    readiness: "Migration Pending",
    risk: "Tour Architecture must migrate here instead of remaining isolated.",
  },
  {
    code: "D",
    key: "explore",
    label: "Explore Siargao Commercial Center",
    href: "/admin/control-tower/explore",
    purpose: "Traveler-facing discovery governance for tours, stays, rentals, food, culture, transport, products, media, and CTA routing.",
    readiness: "Gate Pending",
    risk: "Discovery exposure must not bypass readiness and marketplace controls.",
  },
  {
    code: "E",
    key: "operators",
    label: "Operator Governance",
    href: "/admin/control-tower/operators",
    purpose: "Operator applications, profiles, DOT accreditation, capabilities, approvals, suspensions, team access, and leniency review.",
    readiness: "Gate Pending",
    risk: "Lenient onboarding is allowed; lenient public exposure is not.",
  },
  {
    code: "F",
    key: "accommodations",
    label: "Accommodation Control Center",
    href: "/admin/control-tower/accommodations",
    purpose: "Accommodation profiles, owner onboarding, rooms, availability, booking modes, QR check-in, stays, payouts, and readiness.",
    readiness: "Gate Pending",
    risk: "Raw accommodation imports must not become public bookable inventory.",
  },
  {
    code: "G",
    key: "pricing",
    label: "Pricing & Margin Governance",
    href: "/admin/control-tower/pricing",
    purpose: "Fee matrix, public SRP, operator base rates, platform margin, traveler fees, OTA fees, FX, discounts, payouts, and snapshots.",
    readiness: "Gate Pending",
    risk: "Pricing logic must not live only inside feature pages.",
  },
  {
    code: "H",
    key: "payments",
    label: "Payments, Payouts & Statements",
    href: "/admin/control-tower/payments",
    purpose: "Payment intents, PayMongo status, receipts, refunds, payout holds, operator payouts, accommodation payouts, and statements.",
    readiness: "Gate Pending",
    risk: "Traveler payment pages are not the financial control center.",
  },
  {
    code: "I",
    key: "qr-compliance",
    label: "QR, Compliance & Movement",
    href: "/admin/control-tower/qr-compliance",
    purpose: "QR credentials, QR events, ingress, egress, island hopping, manifests, checkpoints, vessels, exceptions, and manual review.",
    readiness: "Gate Pending",
    risk: "QR must not be reduced to Passport Trail stamps only.",
  },
  {
    code: "J",
    key: "marketplace-exposure",
    label: "Marketplace Exposure Engine",
    href: "/admin/control-tower/marketplace-exposure",
    purpose: "Readiness scores, exposure scores, category pools, placement tiers, fairness rotation, suppression, and placement logs.",
    readiness: "Gate Pending",
    risk: "No flat 85-operator list. No exposure bypassing approval.",
  },
  {
    code: "K",
    key: "ai-assistant",
    label: "AI Assistant Control Center",
    href: "/admin/control-tower/ai-assistant",
    purpose: "Kuya Tala™ personality, allowed knowledge, approved answers, safety rules, language behavior, escalation, and hallucination guards.",
    readiness: "Gate Pending",
    risk: "Kuya Tala™ must not invent prices, inclusions, safety claims, or LGU/DOT statements.",
  },
  {
    code: "L",
    key: "localization",
    label: "Language, Currency & Localization",
    href: "/admin/control-tower/localization",
    purpose: "Local and international language readiness, translation approval, localized QR/payment/safety notes, currency display, and FX readiness.",
    readiness: "Gate Pending",
    risk: "AI translation can assist, but official traveler content must be source-grounded.",
  },
  {
    code: "M",
    key: "api",
    label: "API Control Center",
    href: "/admin/control-tower/api",
    purpose: "API partners, OTA access, Travel & Tours access, tokens, scopes, webhooks, booking intake, QR issuance, and audit logs.",
    readiness: "Gate Pending",
    risk: "API access is governed infrastructure, not open public access.",
  },
  {
    code: "N",
    key: "intelligence",
    label: "Intelligence & Data Center",
    href: "/admin/control-tower/intelligence",
    purpose: "Traveler flow, trip volume, trail demand, tour demand, QR events, operator performance, booking conversion, and LGU/DOT aggregated views.",
    readiness: "Gate Pending",
    risk: "Super Admin intelligence, LGU/DOT intelligence, and operator data must remain separated.",
  },
  {
    code: "O",
    key: "settings",
    label: "System Settings",
    href: "/admin/control-tower/settings",
    purpose: "Users, roles, permissions, navigation, feature flags, auth redirects, platform settings, payment mode, language defaults, and audit settings.",
    readiness: "Gate Pending",
    risk: "Auth redirects and role-aware navigation need a governed home.",
  },
];
