"use client";

import { useEffect, useMemo, useState } from "react";

type ScheduledTrip = {
  id?: string;
  tripNumber?: string;
  routeName?: string;
  routeShortName?: string;
  routeProductCode?: string;
  departureTimeHHmm?: string;
  departureTimeLocal?: string;
  dcsState?: string;
  sourceLabel?: string;
};

type TripPayload = {
  ok?: boolean;
  departureDate?: string;
  dataSource?: string;
  displayMode?: string;
  totalTrips?: number;
  trips?: ScheduledTrip[];
};

const queueStatuses = [
  "NOT_OPEN",
  "QUEUE_FORMING",
  "BOARDING_SOON",
  "BOARDING_NOW",
  "BOARDING_HOLD",
  "CLEARED_FOR_DEPARTURE",
  "DEPARTED",
  "CLOSED",
];

const boardingWindows = ["NOT_STARTED", "OPEN", "PAUSED", "CLOSED"];

const clearanceStatuses = [
  "PENDING",
  "READY_FOR_REVIEW",
  "CLEARED",
  "HELD_BY_LGU",
  "HELD_BY_WEATHER",
  "HELD_BY_PORT",
  "HELD_BY_OPERATOR",
  "CANCELLED",
];

const publicStatuses = [
  "SCHEDULED",
  "BOARDING_SOON",
  "BOARDING_NOW",
  "CLEARED_FOR_DEPARTURE",
  "DEPARTED",
  "DELAY_WATCH",
  "CANCELLED",
];

function deriveServiceNumber(tripNumber: string) {
  const match = tripNumber.match(/^DOT-GL-([A-Z]+)-\d{8}-(\d{4})$/);
  if (!match) return "Service number pending";
  return `GL-${match[1]}-${match[2]}`;
}

function displayTime(trip: ScheduledTrip) {
  return trip.departureTimeHHmm || trip.departureTimeLocal || "Time pending";
}

export default function LguQueueClearancePanel() {
  const [departureDate, setDepartureDate] = useState("2026-06-08");
  const [payload, setPayload] = useState<TripPayload | null>(null);
  const [selectedTripNumber, setSelectedTripNumber] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let active = true;

    setLoading(true);
    fetch(`/api/lgu/dcs/general-luna/scheduled-trips?departureDate=${encodeURIComponent(departureDate)}`, {
      cache: "no-store",
    })
      .then((response) => response.json())
      .then((data: TripPayload) => {
        if (!active) return;
        setPayload(data);
        const firstTripNumber = data.trips?.[0]?.tripNumber || "";
        setSelectedTripNumber((current) => current || firstTripNumber);
      })
      .catch(() => {
        if (!active) return;
        setPayload({ ok: false, trips: [] });
      })
      .finally(() => {
        if (active) setLoading(false);
      });

    return () => {
      active = false;
    };
  }, [departureDate]);

  const trips = useMemo(() => payload?.trips || [], [payload]);
  const selectedTrip = trips.find((trip) => trip.tripNumber === selectedTripNumber) || trips[0];
  const selectedServiceNumber = selectedTrip?.tripNumber
    ? deriveServiceNumber(selectedTrip.tripNumber)
    : "Select scheduled trip";

  return (
    <div style={{ display: "grid", gap: "18px" }}>
      <section style={{ border: "1px solid rgba(5,150,165,0.18)", borderRadius: "28px", background: "linear-gradient(135deg,#ffffff 0%,#f7fefc 52%,#eafbfa 100%)", padding: "22px", boxShadow: "0 22px 60px rgba(1,56,99,0.10)" }}>
        <div style={{ display: "flex", justifyContent: "space-between", gap: "18px", alignItems: "flex-start", flexWrap: "wrap" }}>
          <div>
            <div style={{ display: "inline-flex", border: "1px solid rgba(5,150,165,0.24)", borderRadius: "999px", background: "#eafbfa", color: "#047886", padding: "6px 11px", fontSize: "10px", fontWeight: 850, letterSpacing: "0.17em", textTransform: "uppercase" }}>
              LGU Staff Entry
            </div>
            <h1 style={{ margin: "12px 0 0", color: "#013863", fontSize: "31px", lineHeight: 1.08, letterSpacing: "-0.038em", fontWeight: 790 }}>
              Queue & Clearance Control
            </h1>
            <p style={{ margin: "9px 0 0", maxWidth: "760px", color: "#50668B", fontSize: "14px", lineHeight: 1.58 }}>
              Select a generated scheduled trip, then update queue, boarding, clearance, hold, departure, or cancellation state for the General Luna board.
            </p>
          </div>

          <div style={{ border: "1px solid rgba(5,150,165,0.18)", borderRadius: "22px", background: "#ffffff", padding: "14px 15px", minWidth: "270px", boxShadow: "0 12px 30px rgba(1,56,99,0.07)" }}>
            <div style={{ color: "#50668B", fontSize: "10px", fontWeight: 850, letterSpacing: "0.16em", textTransform: "uppercase" }}>
              Trip Number Source
            </div>
            <div style={{ marginTop: "9px", color: "#013863", fontSize: "14px", fontWeight: 850 }}>
              Generated by OSP-DCS
            </div>
            <div style={{ marginTop: "4px", color: "#50668B", fontSize: "12px", lineHeight: 1.45 }}>
              Staff select scheduled trips. They do not manually invent operating IDs.
            </div>
          </div>
        </div>
      </section>

      <section style={{ display: "grid", gridTemplateColumns: "minmax(320px, 0.98fr) minmax(360px, 1.02fr)", gap: "16px", alignItems: "start" }}>
        <form method="post" action="/api/lgu/dcs/general-luna/queue-clearance" style={{ border: "1px solid rgba(5,150,165,0.18)", borderRadius: "26px", background: "#ffffff", padding: "20px", boxShadow: "0 18px 46px rgba(1,56,99,0.08)", display: "grid", gap: "14px" }}>
          <div>
            <div style={{ color: "#0596A5", fontSize: "10px", fontWeight: 900, letterSpacing: "0.16em", textTransform: "uppercase" }}>
              Staff Control Form
            </div>
            <h2 style={{ margin: "8px 0 0", color: "#013863", fontSize: "21px", lineHeight: 1.18, letterSpacing: "-0.03em", fontWeight: 850 }}>
              Update scheduled trip state
            </h2>
          </div>

          <label style={{ display: "grid", gap: "6px", color: "#013863", fontSize: "12px", fontWeight: 800 }}>
            Departure date
            <input
              type="date"
              value={departureDate}
              onChange={(event) => {
                setDepartureDate(event.target.value);
                setSelectedTripNumber("");
              }}
              style={{ border: "1px solid rgba(5,150,165,0.24)", borderRadius: "14px", padding: "11px 12px", color: "#013863", fontSize: "13px", outline: "none", background: "#f7fefc" }}
            />
          </label>

          <label style={{ display: "grid", gap: "6px", color: "#013863", fontSize: "12px", fontWeight: 800 }}>
            Scheduled trip
            <select
              name="tripNumber"
              required
              value={selectedTripNumber}
              onChange={(event) => setSelectedTripNumber(event.target.value)}
              style={{ border: "1px solid rgba(5,150,165,0.24)", borderRadius: "14px", padding: "11px 12px", color: "#013863", fontSize: "13px", background: "#f7fefc" }}
            >
              {loading && <option value="">Loading scheduled trips...</option>}
              {!loading && !trips.length && <option value="">No generated trips for this date</option>}
              {trips.map((trip) => {
                const tripNumber = trip.tripNumber || "";
                const serviceNumber = deriveServiceNumber(tripNumber);
                return (
                  <option key={tripNumber} value={tripNumber}>
                    {displayTime(trip)} · {trip.routeName || trip.routeShortName || trip.routeProductCode} · {serviceNumber}
                  </option>
                );
              })}
            </select>
          </label>

          <div style={{ border: "1px solid rgba(5,150,165,0.16)", borderRadius: "18px", background: "#f7fefc", padding: "13px 14px" }}>
            <div style={{ display: "flex", justifyContent: "space-between", gap: "12px", alignItems: "center", flexWrap: "wrap" }}>
              <div>
                <div style={{ color: "#50668B", fontSize: "10px", fontWeight: 850, letterSpacing: "0.15em", textTransform: "uppercase" }}>
                  Service Number
                </div>
                <div style={{ marginTop: "4px", color: "#013863", fontSize: "18px", fontWeight: 900 }}>
                  {selectedServiceNumber}
                </div>
              </div>
              <div style={{ textAlign: "right" }}>
                <div style={{ color: "#50668B", fontSize: "10px", fontWeight: 850, letterSpacing: "0.15em", textTransform: "uppercase" }}>
                  Operating ID
                </div>
                <div style={{ marginTop: "4px", color: "#013863", fontSize: "12px", fontWeight: 850 }}>
                  {selectedTrip?.tripNumber || "Generated trip required"}
                </div>
              </div>
            </div>
            <p style={{ margin: "10px 0 0", color: "#50668B", fontSize: "12.5px", lineHeight: 1.5 }}>
              Service numbers repeat by route and time. Operating IDs are unique by date and anchor queue, clearance, QR, manifest, and movement records.
            </p>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: "12px" }}>
            <label style={{ display: "grid", gap: "6px", color: "#013863", fontSize: "12px", fontWeight: 800 }}>
              Queue status
              <select name="queueStatus" defaultValue="BOARDING_SOON" style={{ border: "1px solid rgba(5,150,165,0.24)", borderRadius: "14px", padding: "11px 12px", color: "#013863", fontSize: "13px", background: "#f7fefc" }}>
                {queueStatuses.map((value) => <option key={value} value={value}>{value}</option>)}
              </select>
            </label>

            <label style={{ display: "grid", gap: "6px", color: "#013863", fontSize: "12px", fontWeight: 800 }}>
              Boarding window
              <select name="boardingWindowStatus" defaultValue="OPEN" style={{ border: "1px solid rgba(5,150,165,0.24)", borderRadius: "14px", padding: "11px 12px", color: "#013863", fontSize: "13px", background: "#f7fefc" }}>
                {boardingWindows.map((value) => <option key={value} value={value}>{value}</option>)}
              </select>
            </label>

            <label style={{ display: "grid", gap: "6px", color: "#013863", fontSize: "12px", fontWeight: 800 }}>
              Clearance
              <select name="clearanceStatus" defaultValue="CLEARED" style={{ border: "1px solid rgba(5,150,165,0.24)", borderRadius: "14px", padding: "11px 12px", color: "#013863", fontSize: "13px", background: "#f7fefc" }}>
                {clearanceStatuses.map((value) => <option key={value} value={value}>{value}</option>)}
              </select>
            </label>

            <label style={{ display: "grid", gap: "6px", color: "#013863", fontSize: "12px", fontWeight: 800 }}>
              Board status
              <select name="publicStatus" defaultValue="BOARDING_NOW" style={{ border: "1px solid rgba(5,150,165,0.24)", borderRadius: "14px", padding: "11px 12px", color: "#013863", fontSize: "13px", background: "#f7fefc" }}>
                {publicStatuses.map((value) => <option key={value} value={value}>{value}</option>)}
              </select>
            </label>
          </div>

          <label style={{ display: "grid", gap: "6px", color: "#013863", fontSize: "12px", fontWeight: 800 }}>
            Route note
            <textarea name="routeNote" rows={3} placeholder="Short staff note for operational review" style={{ border: "1px solid rgba(5,150,165,0.24)", borderRadius: "14px", padding: "11px 12px", color: "#013863", fontSize: "13px", outline: "none", background: "#f7fefc", resize: "vertical" }} />
          </label>

          <button type="submit" disabled={!selectedTripNumber} style={{ border: "0", borderRadius: "999px", background: selectedTripNumber ? "linear-gradient(135deg,#F3AE26,#FFD36B)" : "#d7e5e8", color: "#013863", padding: "12px 15px", fontSize: "13px", fontWeight: 900, cursor: selectedTripNumber ? "pointer" : "not-allowed", boxShadow: selectedTripNumber ? "0 12px 28px rgba(243,174,38,0.25)" : "none" }}>
            Save Queue Clearance Update
          </button>
        </form>

        <div style={{ display: "grid", gap: "14px" }}>
          <div style={{ border: "1px solid rgba(5,150,165,0.18)", borderRadius: "24px", background: "#ffffff", padding: "18px", boxShadow: "0 16px 44px rgba(1,56,99,0.075)" }}>
            <div style={{ color: "#0596A5", fontSize: "10px", fontWeight: 900, letterSpacing: "0.16em", textTransform: "uppercase" }}>
              Source Truth
            </div>
            <h3 style={{ margin: "8px 0 0", color: "#013863", fontSize: "18px", lineHeight: 1.2, fontWeight: 850 }}>
              Trip identity is generated upstream
            </h3>
            <p style={{ margin: "8px 0 0", color: "#50668B", fontSize: "13.5px", lineHeight: 1.55 }}>
              OSP-DCS generates scheduled trips from approved route products, departure dates, and schedule slots. Staff control queue and clearance state after the trip exists.
            </p>
          </div>

          <div style={{ border: "1px solid rgba(5,150,165,0.18)", borderRadius: "24px", background: "#ffffff", padding: "18px", boxShadow: "0 16px 44px rgba(1,56,99,0.075)" }}>
            <div style={{ color: "#0596A5", fontSize: "10px", fontWeight: 900, letterSpacing: "0.16em", textTransform: "uppercase" }}>
              Booking Spine Readiness
            </div>
            <h3 style={{ margin: "8px 0 0", color: "#013863", fontSize: "18px", lineHeight: 1.2, fontWeight: 850 }}>
              Bookings attach later
            </h3>
            <p style={{ margin: "8px 0 0", color: "#50668B", fontSize: "13.5px", lineHeight: 1.55 }}>
              Scheduled trips are the operating anchor. Tour, accommodation, voucher, QR, manifest, and movement modules attach into this spine as each module is activated.
            </p>
          </div>

          <a href="/lgu/departure-control/general-luna/board" style={{ display: "inline-flex", width: "fit-content", alignItems: "center", gap: "8px", borderRadius: "999px", background: "#013863", color: "#ffffff", padding: "11px 14px", fontSize: "13px", fontWeight: 850, textDecoration: "none" }}>
            Open GL Port Board -&gt;
          </a>
        </div>
      </section>
    </div>
  );
}
